# Generated by Django 2.1.4 on 2019-01-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_roll', models.IntegerField()),
                ('stu_name', models.CharField(max_length=30)),
                ('stu_city', models.CharField(max_length=30)),
                ('stu_fees', models.FloatField()),
                ('stu_mobile', models.IntegerField()),
                ('stu_address', models.TextField()),
                ('stu_dob', models.DateField()),
                ('stu_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
